"""Functions for working with DataFrame columns.

Note: Array functions are available via fc.arr.* namespace (e.g., fc.arr.size()).
"""

from fenic.api.functions import array as arr
from fenic.api.functions import dt, embedding, json, markdown, semantic, text
from fenic.api.functions.builtin import (
    approx_count_distinct,
    array,
    array_agg,
    array_contains,
    array_size,
    asc,
    asc_nulls_first,
    asc_nulls_last,
    async_udf,
    avg,
    coalesce,
    collect_list,
    count,
    count_distinct,
    desc,
    desc_nulls_first,
    desc_nulls_last,
    first,
    flatten,
    greatest,
    least,
    max,
    mean,
    min,
    stddev,
    struct,
    sum,
    sum_distinct,
    udf,
    when,
)
from fenic.api.functions.core import col, empty, lit, null, tool_param

__all__ = [
    "semantic",
    "text",
    "embedding",
    "arr",
    "array",
    "array_agg",
    "array_contains",
    "array_size",
    "async_udf",
    "avg",
    "approx_count_distinct",
    "collect_list",
    "coalesce",
    "count",
    "count_distinct",
    "json",
    "markdown",
    "max",
    "mean",
    "min",
    "struct",
    "sum_distinct",
    "sum",
    "udf",
    "col",
    "lit",
    "asc",
    "asc_nulls_first",
    "asc_nulls_last",
    "desc",
    "desc_nulls_first",
    "desc_nulls_last",
    "flatten",
    "when",
    "first",
    "stddev",
    "greatest",
    "least",
    "empty",
    "null",
    "tool_param",
    "dt",
]
