# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: substrait/v1/plan.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'substrait/v1/plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fenic.substrait.v1 import algebra_pb2 as substrait_dot_v1_dot_algebra__pb2
from fenic.substrait.v1.extensions import extensions_pb2 as substrait_dot_v1_dot_extensions_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17substrait/v1/plan.proto\x12\x0csubstrait.v1\x1a\x1asubstrait/v1/algebra.proto\x1a(substrait/v1/extensions/extensions.proto\"i\n\x07PlanRel\x12%\n\x03rel\x18\x01 \x01(\x0b\x32\x11.substrait.v1.RelH\x00R\x03rel\x12+\n\x04root\x18\x02 \x01(\x0b\x32\x15.substrait.v1.RelRootH\x00R\x04rootB\n\n\x08rel_type\"\xf6\x03\n\x04Plan\x12/\n\x07version\x18\x06 \x01(\x0b\x32\x15.substrait.v1.VersionR\x07version\x12R\n\x0e\x65xtension_uris\x18\x01 \x03(\x0b\x32+.substrait.v1.extensions.SimpleExtensionURIR\rextensionUris\x12S\n\nextensions\x18\x02 \x03(\x0b\x32\x33.substrait.v1.extensions.SimpleExtensionDeclarationR\nextensions\x12\x33\n\trelations\x18\x03 \x03(\x0b\x32\x15.substrait.v1.PlanRelR\trelations\x12[\n\x13\x61\x64vanced_extensions\x18\x04 \x01(\x0b\x32*.substrait.v1.extensions.AdvancedExtensionR\x12\x61\x64vancedExtensions\x12,\n\x12\x65xpected_type_urls\x18\x05 \x03(\tR\x10\x65xpectedTypeUrls\x12T\n\x12parameter_bindings\x18\x07 \x03(\x0b\x32%.substrait.v1.DynamicParameterBindingR\x11parameterBindings\">\n\x0bPlanVersion\x12/\n\x07version\x18\x06 \x01(\x0b\x32\x15.substrait.v1.VersionR\x07version\"\xa9\x01\n\x07Version\x12!\n\x0cmajor_number\x18\x01 \x01(\rR\x0bmajorNumber\x12!\n\x0cminor_number\x18\x02 \x01(\rR\x0bminorNumber\x12!\n\x0cpatch_number\x18\x03 \x01(\rR\x0bpatchNumber\x12\x19\n\x08git_hash\x18\x04 \x01(\tR\x07gitHash\x12\x1a\n\x08producer\x18\x05 \x01(\tR\x08producer\"|\n\x17\x44ynamicParameterBinding\x12)\n\x10parameter_anchor\x18\x01 \x01(\rR\x0fparameterAnchor\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32 .substrait.v1.Expression.LiteralR\x05valueBn\n\x10\x63om.substrait.v1B\tPlanProtoP\x01\xa2\x02\x03SXX\xaa\x02\x0cSubstrait.V1\xca\x02\x0cSubstrait\\V1\xe2\x02\x18Substrait\\V1\\GPBMetadata\xea\x02\rSubstrait::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substrait.v1.plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.substrait.v1B\tPlanProtoP\001\242\002\003SXX\252\002\014Substrait.V1\312\002\014Substrait\\V1\342\002\030Substrait\\V1\\GPBMetadata\352\002\rSubstrait::V1'
  _globals['_PLANREL']._serialized_start=111
  _globals['_PLANREL']._serialized_end=216
  _globals['_PLAN']._serialized_start=219
  _globals['_PLAN']._serialized_end=721
  _globals['_PLANVERSION']._serialized_start=723
  _globals['_PLANVERSION']._serialized_end=785
  _globals['_VERSION']._serialized_start=788
  _globals['_VERSION']._serialized_end=957
  _globals['_DYNAMICPARAMETERBINDING']._serialized_start=959
  _globals['_DYNAMICPARAMETERBINDING']._serialized_end=1083
# @@protoc_insertion_point(module_scope)
